/// Flutter icons BlueCappedIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BlueCappedIcons
///      fonts:
///       - asset: fonts/BlueCappedIcons.ttf
///
///
///
// ignore_for_file: constant_identifier_names

library;

import 'package:flutter/widgets.dart';

class BlueCappedIcons {
  BlueCappedIcons._();

  static const _kFontFam = 'BlueCappedIcons';
  static const String _kFontPkg = 'bluecapped';

  static const IconData asset =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bolt =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bolt_outlined =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData component =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamation =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unit =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
